// Package tpm handles all communication with the TPM 2.0 hardware chip.
//
// Lives under internal/ — only importable by code within this module.
//
// Core operations are in this file (tpm.go).
// Debugging/inspection utilities are in inspect.go.
package tpm

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"math/big"

	"github.com/google/go-tpm/tpm2"
	"github.com/google/go-tpm/tpm2/transport"
)

// CreateKey is the main provisioning function.
// It follows a create-or-load pattern:
//   - If a key already exists at handleAddr → return its public key (idempotent).
//   - If no key exists → generate one inside the TPM and persist it.
//
// This makes it safe to call on every startup:
// the device always ends up with a key at handleAddr, whether or not it had one before.
// Critical for headless reboot recovery.
//
// Returns the public key as a PEM string. The private key never leaves the TPM.
func CreateKey(tpmPath string, handleAddr uint32) (string, error) {

	t, err := transport.OpenTPM(tpmPath)
	if err != nil {
		return "", fmt.Errorf("opening TPM: %w", err)
	}
	defer t.Close()

	// ── Create-or-load: check first ──────────────────────────────────────────
	//
	// ReadPublic is read-only — safe to call on any handle.
	// If it succeeds, the key exists and we return its public key immediately.
	// If it fails (handle not found), we fall through to creation below.
	//
	// In Python terms:
	//   try:
	//       return read_public_key_pem(t, handle_addr)  # already exists
	//   except TPMError:
	//       pass  # doesn't exist yet, create it
	existingPEM, err := readPublicKeyAsPEM(t, tpm2.TPMHandle(handleAddr))
	if err == nil {
		fmt.Printf("Key already exists at 0x%08X — using existing key.\n\n", handleAddr)
		return existingPEM, nil
	}
	// err != nil here just means "no key at that handle" — not a real error.
	fmt.Printf("No key at 0x%08X — generating new key...\n", handleAddr)

	// ── Step 1: Define the key template ──────────────────────────────────────
	//
	// The template tells the TPM what kind of key to create.
	// Every field is fixed at creation time and cannot be changed later.
	keyTemplate := tpm2.TPMTPublic{
		Type:    tpm2.TPMAlgECC,
		NameAlg: tpm2.TPMAlgSHA256,
		ObjectAttributes: tpm2.TPMAObject{
			FixedTPM:            true,  // bound to this chip — cannot be exported
			FixedParent:         true,  // cannot be moved under a different parent key
			SensitiveDataOrigin: true,  // generated BY the TPM, not imported
			UserWithAuth:        true,  // auth value is empty (= no password, headless)
			NoDA:                true,  // no dictionary attack lockout needed
			SignEncrypt:         true,  // this key can sign data
			Restricted:          false, // can sign ANY data, not just TPM-internal data
			Decrypt:             false,
		},
		Parameters: tpm2.NewTPMUPublicParms(
			tpm2.TPMAlgECC,
			&tpm2.TPMSECCParms{
				Scheme: tpm2.TPMTECCScheme{
					Scheme: tpm2.TPMAlgECDSA,
					Details: tpm2.NewTPMUAsymScheme(
						tpm2.TPMAlgECDSA,
						&tpm2.TPMSSigSchemeECDSA{HashAlg: tpm2.TPMAlgSHA256},
					),
				},
				CurveID: tpm2.TPMECCNistP256,
				KDF:     tpm2.TPMTKDFScheme{Scheme: tpm2.TPMAlgNull},
			},
		),
		// Unique = derivation seed. 32 zero-bytes makes key generation deterministic.
		// Same TPM chip + same owner seed + same template = same key every time.
		// Means: if the persistent slot is deleted, CreatePrimary reproduces the same key.
		Unique: tpm2.NewTPMUPublicID(
			tpm2.TPMAlgECC,
			&tpm2.TPMSECCPoint{
				X: tpm2.TPM2BECCParameter{Buffer: make([]byte, 32)},
				Y: tpm2.TPM2BECCParameter{Buffer: make([]byte, 32)},
			},
		),
	}

	// ── Step 2: Generate the key (transient) ─────────────────────────────────
	//
	// CreatePrimary generates the key inside the TPM under the Owner hierarchy.
	// "Transient" = lives only in TPM RAM until we persist it (Step 4).
	createRsp, err := tpm2.CreatePrimary{
		PrimaryHandle: tpm2.TPMRHOwner, // 0x40000001 = Owner hierarchy
		InPublic:      tpm2.New2B(keyTemplate),
	}.Execute(t)
	if err != nil {
		return "", fmt.Errorf("CreatePrimary: %w", err)
	}

	// Always flush the transient handle — TPM has only ~3 RAM slots.
	// defer = runs right before this function returns, even on error (like finally:).
	defer tpm2.FlushContext{FlushHandle: createRsp.ObjectHandle}.Execute(t) //nolint

	// ── Step 3: Extract and encode the public key ─────────────────────────────
	//
	// Private key stays in TPM silicon permanently.
	// We extract the public key from the response and encode it as PEM.
	pubArea, err := createRsp.OutPublic.Contents()
	if err != nil {
		return "", fmt.Errorf("reading public area: %w", err)
	}
	pemStr, err := eccPubAreaToPEM(pubArea)
	if err != nil {
		return "", err
	}

	// ── Step 4: Persist the key ───────────────────────────────────────────────
	//
	// EvictControl moves the key from transient TPM RAM to non-volatile storage.
	// After this call the key survives reboots until explicitly deleted.
	fmt.Printf("Saving to persistent handle 0x%08X...\n", handleAddr)
	_, err = tpm2.EvictControl{
		Auth:             tpm2.TPMRHOwner,
		ObjectHandle:     tpm2.NamedHandle{Handle: createRsp.ObjectHandle, Name: createRsp.Name},
		PersistentHandle: tpm2.TPMHandle(handleAddr),
	}.Execute(t)
	if err != nil {
		return "", fmt.Errorf("EvictControl at 0x%08X: %w", handleAddr, err)
	}

	fmt.Printf("Key is now persistent at 0x%08X.\n\n", handleAddr)
	return pemStr, nil
}

// ── Private helpers ───────────────────────────────────────────────────────────

// readPublicKeyAsPEM reads the public key at a persistent handle and returns
// it as a PEM string. Returns an error if the handle doesn't exist.
// Used by CreateKey to check whether a key already exists (create-or-load).
func readPublicKeyAsPEM(t transport.TPM, handle tpm2.TPMHandle) (string, error) {
	pubRsp, err := tpm2.ReadPublic{ObjectHandle: handle}.Execute(t)
	if err != nil {
		return "", err // handle doesn't exist or other TPM error
	}
	pub, err := pubRsp.OutPublic.Contents()
	if err != nil {
		return "", fmt.Errorf("unwrapping public area: %w", err)
	}
	return eccPubAreaToPEM(pub)
}

// eccPubAreaToPEM converts a TPMTPublic (must be ECC) to a PEM string.
// Shared by both the creation path and the load path to avoid duplication.
func eccPubAreaToPEM(pub *tpm2.TPMTPublic) (string, error) {
	eccPoint, err := pub.Unique.ECC()
	if err != nil {
		return "", fmt.Errorf("reading ECC point: %w", err)
	}

	// Reconstruct the Go standard-library public key from raw X, Y coordinates.
	// big.Int.SetBytes() reads a byte slice as a big-endian unsigned integer.
	goKey := &ecdsa.PublicKey{
		Curve: elliptic.P256(),
		X:     new(big.Int).SetBytes(eccPoint.X.Buffer),
		Y:     new(big.Int).SetBytes(eccPoint.Y.Buffer),
	}

	// MarshalPKIXPublicKey → DER (binary ASN.1).
	// pem.EncodeToMemory   → base64(DER) wrapped in -----BEGIN PUBLIC KEY-----.
	derBytes, err := x509.MarshalPKIXPublicKey(goKey)
	if err != nil {
		return "", fmt.Errorf("encoding to DER: %w", err)
	}
	return string(pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: derBytes})), nil
}
